# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculadora_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(294, 320)
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Python Codes/calc.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.linea_result = QtWidgets.QLineEdit(Dialog)
        self.linea_result.setGeometry(QtCore.QRect(30, 20, 230, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.linea_result.setFont(font)
        self.linea_result.setToolTip("")
        self.linea_result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.linea_result.setReadOnly(True)
        self.linea_result.setObjectName("linea_result")
        self.push7 = QtWidgets.QPushButton(Dialog)
        self.push7.setGeometry(QtCore.QRect(30, 180, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.push7.setFont(font)
        self.push7.setObjectName("push7")
        self.push8 = QtWidgets.QPushButton(Dialog)
        self.push8.setGeometry(QtCore.QRect(90, 140, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.push8.setFont(font)
        self.push8.setObjectName("push8")
        self.push9 = QtWidgets.QPushButton(Dialog)
        self.push9.setGeometry(QtCore.QRect(150, 140, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.push9.setFont(font)
        self.push9.setObjectName("push9")
        self.push_div = QtWidgets.QPushButton(Dialog)
        self.push_div.setGeometry(QtCore.QRect(210, 140, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.push_div.setFont(font)
        self.push_div.setObjectName("push_div")
        self.push_re = QtWidgets.QPushButton(Dialog)
        self.push_re.setGeometry(QtCore.QRect(150, 100, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.push_re.setFont(font)
        self.push_re.setCheckable(False)
        self.push_re.setChecked(False)
        self.push_re.setObjectName("push_re")
        self.push4 = QtWidgets.QPushButton(Dialog)
        self.push4.setGeometry(QtCore.QRect(30, 140, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.push4.setFont(font)
        self.push4.setToolTip("")
        self.push4.setObjectName("push4")
        self.push5 = QtWidgets.QPushButton(Dialog)
        self.push5.setGeometry(QtCore.QRect(90, 180, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.push5.setFont(font)
        self.push5.setObjectName("push5")
        self.push6 = QtWidgets.QPushButton(Dialog)
        self.push6.setGeometry(QtCore.QRect(150, 180, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.push6.setFont(font)
        self.push6.setObjectName("push6")
        self.push_mult = QtWidgets.QPushButton(Dialog)
        self.push_mult.setGeometry(QtCore.QRect(210, 180, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.push_mult.setFont(font)
        self.push_mult.setObjectName("push_mult")
        self.push2 = QtWidgets.QPushButton(Dialog)
        self.push2.setGeometry(QtCore.QRect(90, 220, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.push2.setFont(font)
        self.push2.setObjectName("push2")
        self.push1 = QtWidgets.QPushButton(Dialog)
        self.push1.setGeometry(QtCore.QRect(30, 220, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.push1.setFont(font)
        self.push1.setObjectName("push1")
        self.push3 = QtWidgets.QPushButton(Dialog)
        self.push3.setGeometry(QtCore.QRect(150, 220, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.push3.setFont(font)
        self.push3.setObjectName("push3")
        self.push_resta = QtWidgets.QPushButton(Dialog)
        self.push_resta.setGeometry(QtCore.QRect(210, 220, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.push_resta.setFont(font)
        self.push_resta.setObjectName("push_resta")
        self.push_punto = QtWidgets.QPushButton(Dialog)
        self.push_punto.setGeometry(QtCore.QRect(30, 260, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.push_punto.setFont(font)
        self.push_punto.setObjectName("push_punto")
        self.push_suma = QtWidgets.QPushButton(Dialog)
        self.push_suma.setGeometry(QtCore.QRect(210, 260, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.push_suma.setFont(font)
        self.push_suma.setObjectName("push_suma")
        self.push_igual = QtWidgets.QPushButton(Dialog)
        self.push_igual.setGeometry(QtCore.QRect(150, 260, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.push_igual.setFont(font)
        self.push_igual.setObjectName("push_igual")
        self.push0 = QtWidgets.QPushButton(Dialog)
        self.push0.setGeometry(QtCore.QRect(90, 260, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.push0.setFont(font)
        self.push0.setObjectName("push0")
        self.push_bo = QtWidgets.QPushButton(Dialog)
        self.push_bo.setGeometry(QtCore.QRect(210, 100, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.push_bo.setFont(font)
        self.push_bo.setObjectName("push_bo")
        self.push_potencia = QtWidgets.QPushButton(Dialog)
        self.push_potencia.setGeometry(QtCore.QRect(90, 100, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.push_potencia.setFont(font)
        self.push_potencia.setObjectName("push_potencia")
        self.push_raiz_cuad = QtWidgets.QPushButton(Dialog)
        self.push_raiz_cuad.setGeometry(QtCore.QRect(30, 100, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.push_raiz_cuad.setFont(font)
        self.push_raiz_cuad.setObjectName("push_raiz_cuad")
        self.push_negativo = QtWidgets.QPushButton(Dialog)
        self.push_negativo.setGeometry(QtCore.QRect(30, 60, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.push_negativo.setFont(font)
        self.push_negativo.setObjectName("push_negativo")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Calculadora"))
        self.linea_result.setText(_translate("Dialog", "0"))
        self.push7.setText(_translate("Dialog", "7"))
        self.push8.setText(_translate("Dialog", "8"))
        self.push9.setText(_translate("Dialog", "9"))
        self.push_div.setToolTip(_translate("Dialog", "División"))
        self.push_div.setText(_translate("Dialog", "/"))
        self.push_re.setToolTip(_translate("Dialog", "Reiniciar valores"))
        self.push_re.setText(_translate("Dialog", "RE"))
        self.push4.setText(_translate("Dialog", "4"))
        self.push5.setText(_translate("Dialog", "5"))
        self.push6.setText(_translate("Dialog", "6"))
        self.push_mult.setToolTip(_translate("Dialog", "Multiplicación"))
        self.push_mult.setText(_translate("Dialog", "x"))
        self.push2.setText(_translate("Dialog", "2"))
        self.push1.setText(_translate("Dialog", "1"))
        self.push3.setText(_translate("Dialog", "3"))
        self.push_resta.setToolTip(_translate("Dialog", "Resta"))
        self.push_resta.setText(_translate("Dialog", "-"))
        self.push_punto.setText(_translate("Dialog", "."))
        self.push_suma.setToolTip(_translate("Dialog", "Suma"))
        self.push_suma.setText(_translate("Dialog", "+"))
        self.push_igual.setToolTip(_translate("Dialog", "Mostrar resultado"))
        self.push_igual.setText(_translate("Dialog", "="))
        self.push0.setText(_translate("Dialog", "0"))
        self.push_bo.setToolTip(_translate("Dialog", "Borrar último dígito"))
        self.push_bo.setText(_translate("Dialog", "BO"))
        self.push_potencia.setToolTip(_translate("Dialog", "Potencia(elevar a)"))
        self.push_potencia.setText(_translate("Dialog", "^"))
        self.push_raiz_cuad.setToolTip(_translate("Dialog", "Raíz cuadrada"))
        self.push_raiz_cuad.setText(_translate("Dialog", "√"))
        self.push_negativo.setToolTip(_translate("Dialog", "Volver dígito(s) negativo"))
        self.push_negativo.setText(_translate("Dialog", "(-)"))

